name: Flutter CI

on:
  push:
  pull_request:

jobs:

  build_android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.0'
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: silversabres.${{ github.sha }}.android
        path: build/app/outputs/flutter-apk/app-release.apk
    
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.0'
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: silversabres.${{ github.sha }}.ios
        path: build/ios/iphoneos/Runner.app